name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/scrum-poker:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /opt/scrum-poker
          
          # Pull latest changes
          git pull origin main
          
          # Pull latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/scrum-poker:latest
          
          # Stop existing containers
          docker-compose down
          
          # Start updated containers
          docker-compose up -d
          
          # Clean up old images
          docker image prune -f
          
          # Verify deployment
          sleep 10
          if ! curl -f http://localhost:5001 > /dev/null 2>&1; then
            echo "Deployment verification failed"
            exit 1
          fi
          
          echo "Deployment successful!"